title:         Koray Mentesoglu  
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //kmentes.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: koraymentesoglu

